In [1]:
num1 = 2
num2 = 3
prod = num1 * num2
prod

6

In [4]:
num = int(input("Enter an integer: "))
factorial = 1

if num == 0:
    print("The factorial of 0 is ", factorial)
elif num < 0: 
    print("Factorial does not exist for negative numbers")
else: 
    for i in range(1, num + 1):
        factorial = factorial*i
    print("The factirial of", num, " is ", factorial)

Enter an integer:  100


The factirial of 100  is  93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


In [7]:
import numpy as np

a_i = np.linspace(1, 10, 10)
a_i

a_i_comprod = np.cumprod(a_i)
np.set_printoptions(suppress=True)
a_i, a_i_comprod

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([      1.,       2.,       6.,      24.,     120.,     720.,
           5040.,   40320.,  362880., 3628800.]))

In [8]:
num1 = 6
num2 = 3

num1/num2

2.0

In [9]:
num1 = 7
num2 = 2
num1%num2

1

In [11]:
import numpy as np

a_col = np.array([[1],[2],[3]])
b_col = 2 * a_col

a_row = np. array([[1,2,3]])
b_row = 2 * a_row
A = np.array([[1,2,3],
              [4,5,6]])
B = 2 * A
a_col, b_col, a_row, b_row, A, B

(array([[1],
        [2],
        [3]]),
 array([[2],
        [4],
        [6]]),
 array([[1, 2, 3]]),
 array([[2, 4, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12]]))

In [13]:
import numpy as np

a_row = np.array([[1,2,3]])
b_row = np.array([[4,3,2]])

a_dot_b = np.inner(a_row, b_row)
a_dot_b

array([[16]])

In [14]:
np.inner(a_row[:], b_row[:])

array([[16]])

In [15]:
np.sum(a_row * b_row)

16

In [16]:
a_col = np.array([[1],[2],[3]])
b_col = np.array([[-1], [0], [1]])

np.inner(a_col, b_col)

array([[-1,  0,  1],
       [-2,  0,  2],
       [-3,  0,  3]])

In [17]:
np.sum(a_col * b_col)

2

In [20]:
import numpy as np

a = np.array([[1,2,3]])
b = np.array([[4,5,6]])

a * b

array([[ 4, 10, 18]])

In [22]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[1,2,3],
              [-1,0,1]])
A*B

array([[ 1,  4,  9],
       [-4,  0,  6]])

In [24]:
import numpy as np
A = np.array([[1,2],
              [3,4]])
B = np.array([[4,2],
             [3,1]])
A@B

array([[10,  4],
       [24, 10]])

In [26]:
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

np.random.seed(7)

m = 6
p = 3
n = 4

A = np.random.uniform(-1,1,m*p).reshape(m, p)
B = np.random.uniform(-1,1,p*n).reshape(p, n)
C = A@B
A, B, C

AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'